// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var React = require("@storybook/react");
var Page$ReactTemplate = require("../src/page.bs.js");

var pageSection = React.storiesOf("Page", (module));

pageSection.add("Test", (function () {
        return ReasonReact.element(/* None */0, /* None */0, Page$ReactTemplate.make("Hello!", /* array */[]));
      }));

exports.pageSection = pageSection;
/* pageSection Not a pure module */
